import React, { useState } from 'react';
import Summary from './components/Summary';
import WordsVsDollars from './components/WordsVsDollars';
import EndlessStudyLoop from './components/EndlessStudyLoop';
import WhereMoneyWent from './components/WhereMoneyWent';
import WhoIsInCharge from './components/WhoIsInCharge';
import { metadata } from './data/dashboardData';

const tabs = [
  { id: 0, label: 'Summary', component: Summary },
  { id: 1, label: 'They cut health spending while praising wellness', component: WordsVsDollars },
  { id: 2, label: 'Delayed 6 months and counting', component: EndlessStudyLoop },
  { id: 3, label: 'What got funded instead', component: WhereMoneyWent },
  { id: 4, label: 'One memo beat 240 residents', component: WhoIsInCharge },
];

export default function App() {
  const [active, setActive] = useState(0);
  
  const handleNavigate = (dashboardId) => {
    setActive(dashboardId);
  };
  
  const ActiveComponent = tabs[active].component;
  
  return (
    <div style={{ 
      maxWidth: 720, 
      margin: '0 auto', 
      padding: '2rem 1.5rem', 
      fontFamily: 'system-ui, -apple-system, sans-serif',
      background: '#fafaf8',
      minHeight: '100vh'
    }}>
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontSize: 20, fontWeight: 500, marginBottom: 6, color: '#222' }}>
          Policy Accountability Dashboards
        </h1>
        <p style={{ fontSize: 13, color: '#888' }}>
          {metadata.jurisdiction}, {metadata.state} — {metadata.focusTopic}
        </p>
        <p style={{ fontSize: 11, color: '#aaa' }}>
          Analysis date: {metadata.analysisDate}
        </p>
      </div>

      {/* Tab Navigation */}
      <div style={{ 
        display: 'flex', 
        gap: 6, 
        flexWrap: 'wrap', 
        marginBottom: 24 
      }}>
        {tabs.map((t) => (
          <button 
            key={t.id} 
            onClick={() => setActive(t.id)} 
            style={{
              padding: '6px 14px', 
              borderRadius: 8, 
              fontSize: 13, 
              cursor: 'pointer',
              border: '1px solid', 
              borderColor: active === t.id ? '#888' : '#ddd',
              background: active === t.id ? '#f5f5f2' : 'white',
              fontWeight: active === t.id ? 500 : 400, 
              color: active === t.id ? '#111' : '#666',
              transition: 'all 0.2s ease'
            }}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* Dashboard Content */}
      <div style={{ 
        background: 'white', 
        border: '1px solid #eee', 
        borderRadius: 12, 
        padding: '1.5rem',
        boxShadow: '0 1px 3px rgba(0,0,0,0.05)'
      }}>
        <h2 style={{ 
          fontSize: 14, 
          textTransform: 'uppercase', 
          letterSpacing: '0.07em', 
          color: '#aaa', 
          marginBottom: 16 
        }}>
          {tabs[active].label}
        </h2>
        
        {active === 0 ? (
          <ActiveComponent onNavigate={handleNavigate} />
        ) : (
          <ActiveComponent />
        )}
      </div>

      {/* Footer */}
      <div style={{ 
        marginTop: 24, 
        textAlign: 'center',
        fontSize: 11,
        color: '#999'
      }}>
        <p>
          Generated by <strong>Oral Health Policy Pulse</strong> — Evidence-based advocacy toolkit
        </p>
        <p style={{ marginTop: 4 }}>
          Methodology: Accountability dashboards using public meeting records and budget data
        </p>
      </div>
    </div>
  );
}
