import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'architecture',
    'quickstart',
    'quick-reference',
    'dashboard',
    {
      type: 'category',
      label: 'Data Sources',
      items: [
        {
          type: 'autogenerated',
          dirName: 'data-sources',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        {
          type: 'autogenerated',
          dirName: 'deployment',
        },
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        {
          type: 'autogenerated',
          dirName: 'development',
        },
      ],
    },
    {
      type: 'category',
      label: 'Case Studies',
      items: [
        {
          type: 'autogenerated',
          dirName: 'case-studies',
        },
      ],
    },
  ],
};

export default sidebars;
