import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'doc',
      id: 'where-is-the-app',
      label: '⚠️ Where is the App?',
    },
    'dashboard',
    {
      type: 'category',
      label: 'Data Sources',
      items: [
        {
          type: 'autogenerated',
          dirName: 'data-sources',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        {
          type: 'autogenerated',
          dirName: 'deployment',
        },
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        {
          type: 'autogenerated',
          dirName: 'development',
        },
      ],
    },
  ],
};

export default sidebars;
